- hosts: localhost
  vars:
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  become: true

  tasks:
    - name: core
      include_tasks: tasks/core.yml
      tags:
        - install

    - name: git
      include_tasks: tasks/git.yml
      tags:
        - install

    - name: zsh
      include_tasks: tasks/zsh.yml
      tags:
        - install
